build-job:
  stage: build
  script:
    - make init-dev-config
    - make run-detached

unit-test:
  stage: test
  script:
    - make test-unit

e2e-test:
  stage: test
  script:
    - make test-e2e

default:
  after_script:
    - make stop

create-docker-images:
  stage: deploy
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker build -t iqbberlin/testcenter-frontend:gitlab -f docker/Dockerfile .;
      docker push iqbberlin/testcenter-frontend:gitlab;
  when: on_success
